### ISSUE TITLE
checkbox-group

### ISSUE THREAD

**Issue by arielbat** [lucasnetau/formBuilder-plugins#4]
I configured this plugin and I get values from my ajax request, working ok, great
How can I use the plugin but checkbox-group instead select?

Thanks

**Comment by arielbat** [comment]
I am trying to get the options by ajax, but can not find the way to make a formbuilder-checkbox with a label

![imagen](https://github.com/user-attachments/assets/a579cf7e-fe14-445c-9d4a-f9955491f982)

**Comment by lucasnetau** [comment]
The customSelect plugin is an example of how data binding can be done. It is hardcoded as a select element due to the fact that the data loading is async and occurs  in the onRender function after formBuilder control has been built (input element creation is normally handled in the build() phase)

You have two options 
1) Modify customSelect to insert the checkbox elements and labels instead of select options. You can see how the plugin creates a placeholder value in the build() phase which is then cloned and inserted into the DOM.
2) Load the data prior to initialising formBuilder/formRender and modify the "values" key of the config.

```javascript
"values": [
      {
        "label": "Option 1",
        "value": "option-1",
        "selected": true
      },
      {
        "label": "Option 2",
        "value": "option-2",
        "selected": false
      }
    ]
```

**Comment by arielbat** [comment]
thanks for your help
CustomSelect for group checkbox is working, just did some dom manipulation. Now I am working on CustomInput plugin
